# This file is generated by Terraformm, do not edit it directly.
# To update it just execute "terraform apply" again after changing the "regions" parameter.

module "regional_resources_af-south-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.af-south-1
  }
}
module "regional_resources_ap-east-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-east-1
  }
}
module "regional_resources_ap-northeast-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-northeast-1
  }
}
module "regional_resources_ap-northeast-2" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-northeast-2
  }
}
module "regional_resources_ap-south-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-south-1
  }
}
module "regional_resources_ap-southeast-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-southeast-1
  }
}
module "regional_resources_ap-southeast-2" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-southeast-2
  }
}
module "regional_resources_ca-central-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ca-central-1
  }
}
module "regional_resources_eu-central-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-central-1
  }
}
module "regional_resources_eu-north-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-north-1
  }
}
module "regional_resources_eu-south-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-south-1
  }
}
module "regional_resources_eu-west-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-west-1
  }
}
module "regional_resources_eu-west-2" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-west-2
  }
}
module "regional_resources_eu-west-3" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-west-3
  }
}
module "regional_resources_me-south-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.me-south-1
  }
}
module "regional_resources_sa-east-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.sa-east-1
  }
}
module "regional_resources_us-east-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-east-1
  }
}
module "regional_resources_us-east-2" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-east-2
  }
}
module "regional_resources_us-west-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-west-1
  }
}
module "regional_resources_us-west-2" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-west-2
  }
}
