# This file is generated by Terraformm, do not edit it directly.
# To update it just execute "terraform apply" again after changing the "regions" parameter.

module "regional_resources_eu-west-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-west-1
  }
}
module "regional_resources_us-east-1" {
  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-east-1
  }
}
